### PR TITLE
feat: sign-in

### PR DESCRIPTION
**Pull request by Ryan-Awad**
MERGE IT NOW!!!!!

### CODE REVIEW

**Comment by JowiAoun** [comment]
NOOOO

**Comment by JowiAoun** [comment]
no

**Comment by HasithDeAlwis** [comment]
@JowiAoun why is this not merged in? Can we reopen?

**Comment by HasithDeAlwis** [comment]
@Ryan-Awad consider a more descriptive commit
try: `feat(ui/auth-modal): reword "Login" to "Sign In"`
Hope this helps :)

**Comment by Ryan-Awad** [comment]
> @Ryan-Awad consider a more descriptive commit
> 
> try: `feat(ui/auth-modal): reword "Login" to "Sign In"`
> 
> Hope this helps :)

no

**Pull request closed without merging**
